version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "${VEC2_REDIS_PORT}:${VEC2_REDIS_PORT}"

  db:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_USER=${VEC2_POSTGRES_USER}
      - POSTGRES_PASSWORD=${VEC2_POSTGRES_PWD}
      - POSTGRES_DB=${VEC2_POSTGRES_DATABASE}
      - POSTGRES_PORT=${VEC2_POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${VEC2_POSTGRES_PORT}:${VEC2_POSTGRES_PORT}"
    expose:
      - ${VEC2_POSTGRES_PORT}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${VEC2_POSTGRES_DATABASE}",
          "-U",
          "${VEC2_POSTGRES_USER}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ["uvicorn", "vec2.app:app", "--host", "0.0.0.0", "--port", "10000"]
    env_file:
      - .env
    ports:
      - "10000:10000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
    driver: local
